# Generated by Django 2.2 on 2021-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenge',
            name='nameuser',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
